name: my_portfolio
description: My po
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.2.0
  camera: ^0.10.5+4
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  hexcolor: ^3.0.1
  gap: ^2.0.1
  flutter_platform_widgets: ^3.3.5
  device_info_plus: ^9.0.2
  flutter_spinkit: ^5.2.0
  dio: ^5.1.2
  dots_indicator: ^3.0.0
  encrypt: ^5.0.1
  file_picker: ^6.0.0
  fdottedline_nullsafety: ^2.0.1
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  pull_to_refresh: ^2.0.0
  flutter_image_compress: ^2.0.4
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  fluttercontactpicker: ^4.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.6
  logger: ^1.3.0
  mockito: ^5.4.0
  network_info_plus: ^4.0.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  pattern_formatter: ^3.0.0
  pdf_render: ^1.3.4
  percent_indicator: ^4.2.3
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.3.1
  screenshot: ^2.0.0
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.4
  store_redirect: ^2.0.1
  supercharged: ^2.1.1
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.11
  dotted_border: ^2.0.0+3
  permission_handler: ^10.0.0
  currency_text_input_formatter: ^2.1.9

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - env/dev.env
    - env/staging.env
    - env/prod.env
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/gifs/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-Black.ttf
